config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mamazon.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mamazon/urls.py
from django.urls import path
from . import views

app_name = 'mamazon'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
]

cart/models.py
from django.db import models
from django.conf import settings
from mamazon.models import Productt

User = settings.AUTH_USER_MODEL

class Cart(models.Model):
    user = models.ForeignKey(User, null=True. blank=True, on_delete=models.CASCADE) # userの会計カートは一つ
    products = models.ManyToManyField() # カートの数は多くてもいい
    total = models.DecimalField(default=0.00, max_digit=9, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

mamazon/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=150)
    price = models.IntegerField()
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='thumbnails/')

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render

# Create your views here.

mamazon/views.py
from django.views.generic import TemplateView, ListView, DetailView
from .models import Product

class Home(TemplateView):
    template_name = 'mamazon/home.html'

class ProductListView(ListView):
    model = Product
    template_name = 'mamazon/list.html'

    def get_queryset(self): # 検索機能
        queryset = Product.objects.all()
        if 'query' in self.request.GET:
            qs = self.request.GET['query']
            queryset = queryset.filter(name__contains=qs)
        return queryset

class ProductDetailView(DetailView):
    model = Product
    template_name = "mamazon/detail.html"

mamazon/templates/mamazon/list.html
{% extends 'mamazon/home.html' %}

{% load static %}

{% block products %}
<li class="span3">
    {% for object in object_list %}
        <div class="thumbnail">
            <a href="{% url 'mamazon:product-detail' object.pk %}"><img src="{{ object.thumbnail.url }}" alt="" /></a>
            <div class="caption">
                <h5>{{ product.name }}/h5>
                <p>
                    {{ object.description }}
                </p>

                <h4 style="text-align:center"><a class="btn" href="{% url 'mamazon:product-detail' object.pk %}"> <i
                            class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i
                            class="icon-shopping-cart"></i></a>
                    <a class="btn btn-primary" href="#">${{ object.price }}</a></h4>
            </div>
        </div>
    {% endfor %}
</li>
{% endblock products %}